---

- name: Ensure sublime Repository key exists
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Ensure APT repository file exists
  apt_repository:
    repo: "deb https://download.sublimetext.com/ apt/stable/"
    state: present
    filename: sublime
  become: true
  become_method: sudo
- name: Ensure sublime is installed
  apt:
    name: sublime-text
    state: present
    update_cache: true
  become: true
  become_method: sudo
