---
- name: Install GPG key for SubLimeText
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present
  become: true
- name: Add specified repositories into sources list using specified filename
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable
    state: present
    filename: sublime
  become: true
- name: Install packages
  apt:
    state: installed
    pkg: sublime-text
    update_cache: yes
  become: true
...
